## Homework 11 PCA
#### Author: Zhili Zhang
#### NetID: zz2382

In [1]:
import numpy as np
np.set_printoptions(suppress=False, precision=6)

In [2]:
X = np.array([[3,2,1],
     [2,4,5],
     [1,2,3],
     [0,2,5]])

In [3]:
# (a)
mean = np.mean(X, axis=0)
print(mean)

[1.5 2.5 3.5]


In [4]:
# (b)
X_bar = X - mean
print(X_bar)

[[ 1.5 -0.5 -2.5]
 [ 0.5  1.5  1.5]
 [-0.5 -0.5 -0.5]
 [-1.5 -0.5  1.5]]


In [5]:
# (b)
Q = 1/4 * np.dot(X_bar.T,X_bar)
print(Q)

[[ 1.25  0.25 -1.25]
 [ 0.25  0.75  0.75]
 [-1.25  0.75  2.75]]


In [6]:
n = X.shape[0]
Xm = X - mean[None, :] # broadcasting
Q = (1/n)*Xm.T.dot(Xm)
print(Q)

[[ 1.25  0.25 -1.25]
 [ 0.25  0.75  0.75]
 [-1.25  0.75  2.75]]


In [7]:
lam, V = np.linalg.eigh(Q)
print(lam)
print(V)

[0.014955 1.17338  3.561665]
[[ 0.593635  0.666772 -0.450569]
 [-0.664722  0.721872  0.192472]
 [ 0.453589  0.185245  0.871746]]


In [9]:
Xt = np.random.normal(0,1,(6,3))
print(Xt)

[[-0.146711  2.038739  0.301776]
 [-0.955846  0.245126 -1.075544]
 [ 0.318936  0.470523  0.512264]
 [ 0.997884 -1.433896  0.305191]
 [-0.342551  0.590055  1.709024]
 [ 1.558143 -1.89701   1.242184]]


In [10]:
Zt = (Xt - mean[None, :]).dot(V)
print(Zt)

[[-2.121613 -2.023407 -2.134863]
 [-2.034427 -4.112816 -3.316186]
 [-0.707287 -2.805986 -2.463015]
 [ 0.867742 -3.76639  -3.315991]
 [-0.636588 -2.939067 -1.098691]
 [ 1.933184 -3.55356  -2.840743]]


In [11]:
Xthat = Zt.dot(V.T)+mean[None,:]
print(Xthat)

[[-0.146711  2.038739  0.301776]
 [-0.955846  0.245126 -1.075544]
 [ 0.318936  0.470523  0.512264]
 [ 0.997884 -1.433896  0.305191]
 [-0.342551  0.590055  1.709024]
 [ 1.558143 -1.89701   1.242184]]


In [12]:
Xthat = Zt[:,:2].dot(V[:,:2].T) + mean[None,:]

In [13]:
Xerr = np.sum((Xt - Xthat)**2, axis=1)
Xerr

array([ 4.557641, 10.99709 ,  6.066442, 10.995798,  1.207123,  8.069821])

In [14]:
print(Zt[:,2]**2)

[ 4.557641 10.99709   6.066442 10.995798  1.207123  8.069821]


In [8]:
# (c)
w, v = np.linalg.eig(Q)
print(w)
print(v)

[3.561665 1.17338  0.014955]
[[-0.450569 -0.666772 -0.593635]
 [ 0.192472 -0.721872  0.664722]
 [ 0.871746 -0.185245 -0.453589]]


In [85]:
# (d)
pca_coef = np.dot(v.T, X_bar.T)
print(pca_coef.T)

[[-2.951456 -0.17611  -0.088842]
 [ 1.371043 -1.694062  0.019882]
 [-0.306825  0.786944  0.191251]
 [ 1.887237  1.083227 -0.122291]]


In [79]:
# (e)
X_recon = np.dot(v, pca_coef).T + mean
print(X_recon)

[[3.000000e+00 2.000000e+00 1.000000e+00]
 [2.000000e+00 4.000000e+00 5.000000e+00]
 [1.000000e+00 2.000000e+00 3.000000e+00]
 [8.881784e-16 2.000000e+00 5.000000e+00]]


In [81]:
# (f)
X_approx = np.dot(v[:,:2], pca_coef[:2,:]).T+mean
print(X_approx)

[[ 2.94726   2.059055  0.959702]
 [ 2.011803  3.986784  5.009018]
 [ 1.113533  1.872871  3.086749]
 [-0.072596  2.081289  4.94453 ]]


In [82]:
# (g)
err = (X - X_approx)**2
print(err)

[[2.781486e-03 3.487523e-03 1.623909e-03]
 [1.393013e-04 1.746608e-04 8.132800e-05]
 [1.288982e-02 1.616171e-02 7.525441e-03]
 [5.270204e-03 6.607965e-03 3.076893e-03]]


In [98]:
pca_coef = pca_coef.T
mean_coef = np.mean(pca_coef, axis=0)
coef_bar = pca_coef - mean_coef
cov_coef = np.dot(coef_bar.T, coef_bar)
print(np.dot(coef_bar.T, coef_bar))
print(np.true_divide(cov_coef, 4))

[[ 1.424666e+01  2.692473e-15  1.964440e-15]
 [ 2.692473e-15  4.693521e+00 -2.266327e-15]
 [ 1.964440e-15 -2.266327e-15  5.982025e-02]]
[[ 3.561665e+00  6.731182e-16  4.911100e-16]
 [ 6.731182e-16  1.173380e+00 -5.665818e-16]
 [ 4.911100e-16 -5.665818e-16  1.495506e-02]]


In [99]:
print(mean_coef.T)
#print(np.dot(mean_coef.T, pca_coef))

[-5.551115e-17  5.551115e-17 -1.387779e-17]
